---
- hosts: "{{ hostname }}"
  become: yes
  vars_files: "../../vars/main.yaml"
  vars:
    hostname: "loadbalancer"
  tasks:
    - name: Copy Nginx Config
      template:
        src: ../../templates/nginx.conf.j2
        dest: "/home/{{ my_user }}/nginx.conf"
    - name: Docker Stop & Remove Containers
      shell: |
        docker stop $(docker ps -aq) && \
        docker rm $(docker ps -aq) && \
        docker image rm $(docker image ls -aq)
      ignore_errors: yes
    - name: Docker Start nginx Load Balancer
      shell: |
        docker run --restart always -d -p 80:80 -v /home/{{ my_user }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro nginx