---
- hosts: "{{ hostname }}"
  become: yes
  vars_files: ../../vars/main.yaml
  vars:
    project_root: "/var/www-git/"
    hostname: "all"
  tasks:
    - name: Pull Git Repo
      git:
        repo: "{{ repo_name }}"
        dest: "{{ project_root }}"
        update: yes
        version: "{{ repo_branch }}"
    