---
- hosts: all
  become: yes
  vars_files: ../vars/main.yaml
  vars:
    project_root: "/var/www-git/"
  #   repo_name: "https://github.com/codingforentrepreneurs/iac-python"
  #   project_root: "/var/www/"
  #   repo_branch: main
  tasks:
    - name: Update Apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Pull Git Repo
      git:
        repo: "{{ repo_name }}"
        dest: "{{ project_root }}"
        update: yes
        version: "{{ repo_branch }}"
    