---
- hosts: all
  become: yes
  vars_files: ../vars/main.yaml
  vars:
    project_root: "/var/www-git/"
  tasks:
    - name: Update Apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400