---
- hosts: webapps
  become: yes
  vars_files: ../../vars/main.yaml
  tasks:
    - name: Docker Stop & Run Containers
      shell: |
        docker stop $(docker ps -aq) && \
        docker run -d -e PORT=8001 -p 80:8001 webapp
