---
- hosts: webapps
  become: yes
  vars_files: ../../vars/main.yaml
  tasks:
    - name: Build
      command: docker build -t webapp -f {{ project_root }}Dockerfile {{ project_root }}
    - name: Run
      command: docker run -d -e PORT=8001 -p 80:8001 webapp