---
- hosts: webapps
  become: yes
  vars_files: ../../vars/main.yaml
  tasks:
    - name: Run
      command: docker run -d -e PORT=8001 -p 80:8001 webapp
    - name: Firewall for ssh & port 80
      ufw: rule=allow port={{ item }} proto=tcp
      loop: [80, 22]
    # - name: Set firewall
    #   ufw: state=enabled
    #   become: true
